from cmds import *

cmds = {"dp":	  display_f,
		"dpl":	  displayl_f,
		"loop":   loop_f,
		"new":    new_f,
		"set":    set_f,
		"stt":    state_f,
		"end":    end_f,
		"clr":    clear_f,
		"del":    delete_f,
		"exec":   execute_f,
		"add":    add_f,
		"sub":    sub_f,
		"mul":	  mul_f,
		"div": 	  div_f,
		"pow":	  pow_f,
		"help":   help_f,
		"fun":    fun_f,
		"ret":    ret_f,
		"vr":  	  vr_f,
		"call":	  call_f,
		"enable_eq" : enable_err_quit_f,
		"disable_eq": disable_err_quit_f
		}